SUBPRJ=cmade rvpdump rvpdump_t vc hb ngrt
#SUBPRJ+=ngrt personality sigsim hb
INTERNALLIBS=librvread vc ngrt
LIBDEPS+=librvread:rvpdump librvread:rvpdump_t librvread:hb vc:hb

.include <mkc.subprj.mk>
