SUBPRJ=cmade ngrt personality rvpdump sigsim hb
INTERNALLIBS=librvu librvread vc
LIBDEPS=librvu:librvread
LIBDEPS+=vc:hb librvread:hb
LIBDEPS+=librvu:ngrt librvread:rvpdump librvu:rvpdump

.include <mkc.subprj.mk>
