SUBPRJ=atomic_load atomic_store gnutest_sig interrupt_mask_change limits
SUBPRJ+=mask natest rmw load store unaligned xchange_t816 xchange_test
SUBPRJ+=memset memcpy memmove

.include <mkc.subprj.mk>
