SUBPRJ=atomic_load atomic_store
SUBPRJ+=gnutest_sig interrupt_mask_change limits
SUBPRJ+=mask natest rmw load store unaligned xchange_t816 xchange_test
SUBPRJ+=memcpy
#SUBPRJ+=memmove
#SUBPRJ+=memset
SUBPRJ+=__sysv_signal
SUBPRJ+=signal

.include <mkc.subprj.mk>
