.if $(OS:Uunknown) == QNX
LIBDIR=$(PREFIX)/lib/qnx
.endif

.if defined(CROSS_OBJTOP)
MAKEOBJDIR='$$(.CURDIR:C,${CROSS_SRCTOP},${CROSS_OBJTOP},)'
MAKEFLAGS+=	MAKEOBJDIR='$$(.CURDIR:C,${CROSS_SRCTOP},${CROSS_OBJTOP},)'
.endif

#.warning CROSS_SRCTOP=$(CROSS_SRCTOP) CROSS_OBJTOP=$(CROSS_OBJTOP) .OBJDIR=$(.OBJDIR) MAKEFLAGS=$(MAKEFLAGS)
