STRIPFLAG=-s
MANDIR=${PREFIX}/share/man

.if $(.CURDIR:C,.*/ctests.*,,) != "" && $(NBINSTALL:Unone) != "none"
INSTALL:=$(NBINSTALL)
LN:=$(NBINSTALL) -l h
LN_S:=$(NBINSTALL) -l s
BINOWN=root
BINGRP=root
FILESOWN=root
FILESGRP=root
LIBOWN=root
LIBGRP=root
MANOWN=root
MANGRP=root
.endif
