#
#
.include "../head.mk"
MKCOVERAGE=no
PROG=gnutest_sig
CTESTS_DIR=$(.CURDIR)/../..
# _POSIX_C_SOURCE=200809L is needed for SA_RESETHAND on Linux
CPPFLAGS+="-D_POSIX_C_SOURCE=200809L"

.include "../tail.mk"
