.include "../../head.mk"
PATH:=$(.OBJDIR)/../../../toolset/bin:$(PATH)
LOCAL_NORMALIZE=$(.CURDIR)/../../../normalize-lines
CPPFLAGS+=-I$(.CURDIR)/../../../../include
CTESTS_DIR=$(.CURDIR)/../../..

PROG=and

.include "../../tail.mk"
