#!/bin/sh

rverror()
{
	sharedir=$(dirname $0)/../share/rv-predict-c

	min_major="1"
	min_minor="8"

	if which java >/dev/null; then
		# found java executable in PATH
		_java=java
	elif [ -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ];  then
		# found java executable in JAVA_HOME
		_java="$JAVA_HOME/bin/java"
	else
		cat 1>&2 <<EOF
RV Predict requires Java ${min_version} to run but Java was not detected.
Please either add it to PATH or set the JAVA_HOME environment variable.
EOF
		exit 1
	fi

	version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')

	major=$(echo $version | sed 's/^\([0-9]\+\)\..*$/\1/')
	minor=$(echo $version | sed 's/^[0-9]\+\.\([0-9]\+\).*$/\1/')

	if [ "$major" -lt "$min_major" -o "$major" -eq "$min_major" -a "$minor" -lt "$min_minor" ]; then
		cat 1>&2 <<EOF
RV-Predict/C requires Java $min_version to run but the detected version
is $version.  Please either add Java $min_version bin directory to the PATH
or set the JAVA_HOME environment variable accordingly.
EOF
		exit 2
	fi

	${_java} -ea -cp ${sharedir}/rv-predict.jar com.runtimeverification.error.RVError "$@"
}

metadata=$(tempfile)
trap "rm -rf $metadata" EXIT INT TERM
printf '{"suppressions":[{"condition":["Category","LintError"],"suppress":false}],"message_length":80,"format":"Console","previous_errors":[],"fatal_errors":false,"rv_error":""}\n' > $metadata
while read -r line
do
  printf '%s' "$line" | rverror $metadata
done
