#
# This makefile uses mk-configure macro files
# (https://github.com/cheusov/mk-configure) with BSD make.  On a
# POSIX-compliant platforms like Linux, Mac OS X, or *BSD, I recommend
# installing bmake and mk-configure from pkgsrc.org. bmake is in the
# pkgsrc bootstrap kit. The package for mk-configure is in devel/.
#

NOMAN=
FILESMODE=0644
FILES=ldscript
FILESDIR=$(DATADIR)/rv-predict-c

.include <mkc.files.mk>
