#
# This makefile uses mk-configure macro files
# (https://github.com/cheusov/mk-configure) with BSD make.  On a
# POSIX-compliant platforms like Linux, Mac OS X, or *BSD, I recommend
# installing bmake and mk-configure from pkgsrc.org. bmake is in the
# pkgsrc bootstrap kit. The package for mk-configure is in devel/.
#

LIB=rvprt32

CFLAGS+=-m32 # -Wl,-m32 -Wl,-m -Wl,elf_i386
LDFLAGS+=-m32
CPPFLAGS+=-Wuninitialized

.include "Makefile"
