.include "../../head.mk"
PATH:=$(.OBJDIR)/../../../toolset/bin:$(PATH)
POST_NORMALIZE=$(.CURDIR)/../../../normalize-lines
CPPFLAGS+=-I$(.CURDIR)/../../../../include
CTESTS_DIR=$(.CURDIR)/../../..

PROG=xor

.include "../../tail.mk"
