.include "../../head.mk"
PATH:=$(.OBJDIR)/../../../toolset/bin:$(PATH)
LOCAL_NORMALIZE=$(.CURDIR)/normalize
CPPFLAGS+=-I$(.CURDIR)/../../../../include
CTEST_dir=../../..

PROG=xor

.include "../../tail.mk"
