/*******************************************************************************
 * Copyright (c) 2013 University of Illinois
 * 
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 * 
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
package edu.uiuc.run;

import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.Method;

import db.DBEngine;

import rvpredict.logging.ReplayRT;

/**
 * The entry class to replay the application for exposing data races.
 * For each race, the corresponding racey schedule generated by 
 * rv-predict-engine are enforced at replay to deterministically
 * create the race.
 *  
 * @author jeffhuang
 *
 */
public class Main {
	
	/**
	 * The args contains the application name, arguments, and the id fo 
	 * the race schedule. If the id is not specified, all schedules in the 
	 * database are explored.
	 * 
	 * @param args
	 */
	public static void main(String[] args)
	{
		if(args.length==0)
		{
			System.err.println("please specify the application name");
		}
		else 
		{
			run(args);
		}
}
		
private static void run(String[] args)
{
	try 
	{		
		String appname = args[0];
		DBEngine db = new DBEngine(appname);
		int size = db.getScheduleSize();
		
		//the second argument is the schedule id
		if(args.length>1)
		{
			int id = Integer.valueOf(args[1]);
			Object[] schedule = null;
			if(id<=size) schedule = db.getSchedule(id);
			db.closeDB();
			if(schedule==null)
			{
				//no schedule to replay, just terminate
				System.exit(0);
			}
			
			ReplayRT.init(appname,schedule);
	
			Class<?> c = Class.forName(appname);
			
		    Class[] argTypes = new Class[] { String[].class };
		    Method main = c.getDeclaredMethod("main", argTypes);
		   
		    String[] mainArgs = {};
	
		    if(args.length>1)
		    {
		    	mainArgs = new String[args.length-1];
		    	for(int k=0;k<args.length-1;k++)
		    		mainArgs[k] = args[k+1];
		    }
		    
		    System.out.println("\n------------ Replaying "+appname+" with schedule "+id+" ---------------\n");
		    
		    main.invoke(null, (Object)mainArgs);
			// production code should handle these exceptions more gracefully
		}
		else
		{
			//TODO: test this part
			
			//if the schedule id is not specified, we will explore all schedules in the database
			db.closeDB();
			for(int id=1;id<=size;id++)
			{
				ProcessBuilder pb = new ProcessBuilder("java", "-cp", "tmp/replay:rv-replayer.jar", "edu.uiuc.run.Main",appname+" "+id);
				pb.redirectErrorStream();
				
				InputStream is = null;
		        try {

		            Process process = pb.start();
		            process.waitFor();
		            
		            is = process.getInputStream();

		            int value;
		            while ((value = is.read()) != -1) {

		                char inChar = (char)value;
		                System.out.print(inChar);

		            }

		        } catch (IOException ex) {
		            ex.printStackTrace();
		        }        

			}
		    
		}
		}catch (Exception x) {
			    x.printStackTrace();
			}
		}
}
