#!/bin/sh

more<<END-OF-LICENSE
--------------------------------------------------------------------------------
RUNTIME VERIFICATION "AS IS" 30-DAY EVALUATION LICENSE AGREEMENT (NON
PRODUCTION LICENSE)
--------------------------------------------------------------------------------

This license is an agreement between Runtime Verification, Inc. (RV)
and you. It applies to the software provided by RV that included this
license, as well as to updates, supplements, Internet-based and support
services, unless other terms accompany those items. If so, those terms
apply.

By using the software, you accept these terms. If you do not accept
them, do not use the software.  Instead, contact Runtime Verification
Support (http://runtimeverification.com/support).

1. OVERVIEW.
   a. The software includes development tools, software programs and
      documentation.
   b. The software is licensed for 30-day evaluation based on a per
      processor core basis. Each evaluation license permits you to run
      the software on up to eight (8) processor cores.

2. INSTALLATION AND USE.
   a. You may install one copy of the software on a single server in
      your organization to design, develop, test and demonstrate your
      programs.
   b. You may only run each licensed copy of the software on up to eight
      (8) processor cores.
   c. You may only use this software and its results for review and
      evaluation purposes only, and not in connection with production
      code.

3. LICENSE. You have limitted rights to use this software. RV reserves
   all other rights. You may not
   * Make more copies of the software than specified in this agreement;
   * Publish the software for others to copy;
   * Transfer, assign, rent, lease or lend the software; 
   * Work around any technical limitations in the software;
   * Reverse engineer, decompile/disassemble, or create derivative works
     of the software nor permit any third party to do so, except to the
     extent such restrictions are prohibited by applicable mandatory
     local law.
   * Use the software for commercial software hosting services.
   * Use the software of its results once the 30-day evaluation period
     expires.
   * Use the software to correct any bugs or defects in your company's
     commercial code base (no production use).  To engage in production
     use, you must purchase a different license.  Please see
     https://runtimeverification.com/licensing for details.

4. BACKUP COPY. You may make one backup copy of the software. You may
   use the backup copy only to reinstall the software.

5. THIRD PARTY SOFTWARE. The software may contain permitted open source
   or community software provided under separate licenses.  Such
   licenses, if any, can found under a folder named "Licenses".

5. SUPPORT SERVICES. RV provides limited support services for the
   software.  Please check our website and/or contact us at [Runtime
   Verification Support](http://runtimeverification.com/support).

6. APPLICABLE LAW. The laws of the country in which you acquired the
   software govern the interpretation of this agreement and apply to
   claims for breaching it, regardless of conflict of laws principles.

7. LIMITATION ON AND EXCLUSION OF DAMAGES. You can recover from RV only
   direct damages up to the amount you paid for the software. You cannot
   recover any other damages, including consequential, lost profits,
   special, indirect or incidental damages. This limitation applies to
   * anything related to the software, services, content (including
     code) on third party Internet sites, or third party programs; and
   * claims for breach of contract, breach of warranty, guarantee or
     condition, strict liability, negligence, or other tort to the
     extent permitted by applicable law.
   It also applies even if
   * repair, replacement or a refund for the software does not fully
     compensate you for any losses; or
   * RV knew or should have known about the possibility of the damages.

--------
WARRANTY
--------

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

If you do not accept the license, installation will be cancelled.

END-OF-LICENSE

read -p "Do you accept the license? [y/n] " yn

if [ x${yn%%[yY]} = x ]; then
	echo "License accepted.  Continuing."
	exit 0
else
	echo "Not accepted.  Cancelling installation."
	exit 1
fi
