Document: rv-predict-c
Title: Debian rv-predict-c Manual
Author: <insert document author here>
Abstract: This manual describes what rv-predict-c is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rv-predict-c/rv-predict-c.sgml.gz

Format: postscript
Files: /usr/share/doc/rv-predict-c/rv-predict-c.ps.gz

Format: text
Files: /usr/share/doc/rv-predict-c/rv-predict-c.text.gz

Format: HTML
Index: /usr/share/doc/rv-predict-c/html/index.html
Files: /usr/share/doc/rv-predict-c/html/*.html
