#!/usr/bin/env bash
if java -version 2>&1 | grep "64-Bit" >& /dev/null; then
  ARCH=64;
else
  ARCH=32;
fi

RV_PREDICT_LIB_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ `uname` = 'Darwin' ]; then
  export PATH="$RV_PREDICT_LIB_DIR/native/osx":$PATH
  export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:"$RV_PREDICT_LIB_DIR/native/osx"
elif [[ `uname` == *MINGW* || `uname` == *MSYS* || `uname` == *CYGWIN* ]]; then
  export PATH="$RV_PREDICT_LIB_DIR/native/windows":"$RV_PREDICT_LIB_DIR/native/windows$ARCH":"$RV_PREDICT_LIB_DIR/native/$ARCH":$PATH
else
  if [ `uname` != 'Linux' ]; then
    echo "Warning: unsupported OS detected. Defaulting to Linux mode, but errors may occur." 1>&2
  fi
  export PATH="$RV_PREDICT_LIB_DIR/native/linux":"$RV_PREDICT_LIB_DIR/native/linux$ARCH":$PATH
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"$RV_PREDICT_LIB_DIR/native/linux$ARCH"
fi

export CYGWIN=nodosfilewarning
