#!/bin/sh

grep -v 'change of generation -> [[:digit:]]\+$' | \
grep -v ' memoize signal mask #' | \
sed 's/{0x[0-9a-z]\+}/{}/g' | \
sed 's/ generation [0-9]\+$//g' | \
sed 's/cfa [0-9a-z]\+ /cfa . /g'
