NOMAN=
#
# This makefile uses mk-configure macro files
# (https://github.com/cheusov/mk-configure) with BSD make.  On a
# POSIX-compliant platforms like Linux, Mac OS X, or *BSD, I recommend
# installing bmake and mk-configure from pkgsrc.org. bmake is in the
# pkgsrc bootstrap kit. The package for mk-configure is in devel/.
#

FILESMODE=0755
FILES=rvpc.sh rvpsymbolize.sh rvpx.sh
FILESNAME_rvpc.sh=rvpc
FILESNAME_rvpsymbolize.sh=rvpsymbolize
FILESNAME_rvpx.sh=rvpx
LINKS=${BINDIR}/rvpc ${BINDIR}/rvpc++

.include <mkc.files.mk>
