.Dd July 20, 2017
.Dt RVPA 1
.Os Linux
.Sh NAME
.Nm rvplicense
.Nd prompt for email and password and then fetch an
.Tn RV-Predict/C
license key
.Sh SYNOPSIS
.Nm 
.Sh DESCRIPTION
.Nm
looks for a valid license key.
Finding one, it exits.
Finding none, it
prompts the user for the email and password that they registered at
.Tn Runtime Verification, Inc.
Then it tries to fetch a new license key from the company's servers.
.Pp
.Tn RV-Predict/C
will not perform data-race prediction without a valid license key,
so to make use of
.Nm rvpa
and
.Nm rvpx ,
a valid license key must be in place.
.Sh FILES
.Bl -tag -width "/usr/share/rv-predict-c/PRODUCT_KEY"
.It Pa /usr/share/rv-predict-c/PRODUCT_KEY
.Nm
looks for a site-wide product key here.
.It Pa $HOME/.config/runtime-verification/predict/PRODUCT_KEY
.Nm
looks for a user's product key here.
.El
.Sh EXAMPLES
Fetch an
.Tn RV-Predict/C
license key for john@doe.com:
.Bd -literal
$ rvplicense
This product has no license on file.
Please sign up for a license at https://runtimeverification.com/licensing.

Once you obtain a valid license, please login with your RV account:
Enter your e-mail: john@doe.com
Enter your RV password: 
.Ed
.Sh EXIT STATUS
.Nm
returns 0 on success, 1 on failure.
.Sh SEE ALSO
.Xr rvpa 1 ,
.Xr rvpx 1
.Sh HISTORY
.Tn RV-Predict/C
2.0 was released in July 2017.
.Sh AUTHORS
.\" .An "Yilong Li"
.\" .An "Traian Serbanuta"
.\" .An "Virgil Serbanuta"
.\" .An "David Young" Aq david.young@runtimeverification.com
.An "Runtime Verification, Inc." Aq support@runtimeverification.com
.Sh BUGS
This version of
.Nm
does not provide line-editing functions, sorry.
