#!/bin/bash
set -e

image="rv-predict-ubuntu"

# build the docker image 
docker build -t $image -f  `pwd`/docker/Dockerfile `pwd`/docker

# run install-in-container script
docker run -v `pwd`:/root/rv-predict --rm $image /root/rv-predict/installer/scripts/install-in-container