#!/bin/bash
set -e

container="rv-predict-installer-test-$(date +%s)"
source_container="ubuntu-1604-java"

function stopLxc {
  lxc stop $container
}
unset XDG_SESSION_ID
unset XDG_RUNTIME_DIR
unset XDG_SESSION_COOKIE

lxc copy $source_container $container -e && trap stopLxc EXIT
lxc config device add $container rv-predict-test disk source=`pwd` path=/mnt/jenkins/
lxc start $container
lxc exec $container -- su -l -c /mnt/jenkins/installer/scripts/install-in-container
