.include "../../head.mk"
PATH:=$(.OBJDIR)/../../../toolset/bin:$(PATH)
LOCAL_NORMALIZE=$(.CURDIR)/../../../normalize-lines
CPPFLAGS+=-I$(.CURDIR)/../../../../include
CTEST_dir=../../..

PROG=or

.include "../../tail.mk"
