/*******************************************************************************
 * Copyright (c) 2013 University of Illinois
 *
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *
 * 1. Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 * notice, this list of conditions and the following disclaimer in the
 * documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
package com.runtimeverification.rvpredict.runtime;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.MethodHandles;
import java.lang.reflect.Field;
import java.util.Collection;
import java.util.Collections;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.ListIterator;
import java.util.Map;
import java.util.Set;
import java.util.Vector;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.function.Supplier;

import org.apache.commons.lang3.mutable.MutableInt;

import com.runtimeverification.rvpredict.config.Configuration;
import com.runtimeverification.rvpredict.log.EventType;
import com.runtimeverification.rvpredict.log.ILoggingEngine;
import com.runtimeverification.rvpredict.metadata.Metadata;
import com.runtimeverification.rvpredict.util.Constants;

/**
 * RV-Predict runtime library that consists of instrumented methods for logging
 * trace events.
 * <p>
 * The instrumented methods are carefully designed to make sure that the logged
 * trace must satisfy the following properties:
 * <ul>
 * <li><b>Program order + Start/Join constraint</b>
 * <p>
 * Therefore, {@link EventType#START} and {@link EventType#PRE_JOIN} must be
 * logged before {@link Thread#start()} and {@link Thread#join()} respectively,
 * while {@link EventType#JOIN}, {@link EventType#JOIN_MAYBE_FAILED} must be
 * logged after {@link Thread#join()}.
 *
 * <li><b>Lock mutual exclusion</b>
 * <p>
 * Lock events must be logged after acquiring the lock, while unlock events must
 * be logged before releasing the lock.
 *
 * <li><b>Interrupt|Interrupted constraint</b>
 * <p>
 * Write on interrupted status generated by {@link Thread#interrupt()} must be
 * logged before the read-then-clear of interrupted status generated by blocking
 * method throwing the {@link InterruptedException}.
 * </ul>
 *
 * <b>Note:</b> we do not, however, guarantee absolute read-write consistency of
 * the logged trace because the running problem could be racey itself. For
 * example, suppose two read and write operations on shared variable {@code x}
 * are racey, the following scenarios are possible:
 *
 *
 *  TODO(YilongL): here is a mistake, read event is logged after the read happens!
 *  reconsider the following examples and conclusion
 * <pre>
 * read-write race:  log(write, x, 1) ~> log(read, x, 0) ~> write(x, 1) ~> read(x, 1), where initValue(x) = 0
 * write-write race: log(write, x, 1) ~> log(write, x, 2) ~> write(x, 2) ~> write(x, 1), where initValue(x) = 0
 * </pre>
 *
 * Even worse, the data race in the program causes our logger to log events that
 * deviate from actual execution.
 * <p>
 * Nevertheless, we do guarantee the soundness of our prediction algorithm
 * <em>at least</em> up till the point that data races in the program mess up
 * the trace because 1) for each trace window, our prediction algorithm doesn't
 * care about the order of events from different threads as we are going to
 * reorder them anyway, and 2) the (incorrectly logged) final values of the
 * racey window <em>might</em> still be a possible outcome that can be inferred
 * from the actual execution.
 *
 * @see EventType
 *
 * @author YilongL
 *
 */
@SuppressWarnings({ "unchecked", "rawtypes" })
public final class RVPredictRuntime implements Constants {

    private static final String MOCK_STATE_FIELD = "$state";

    public static final Metadata metadata = Metadata.singleton();

    /**
     * <em>Interruption rule:</em> A thread calling interrupt on another thread
     * happens before the interrupted thread detects the interrupt (either by
     * having {@code InterruptedException} thrown, or invoking
     * {@link Thread#isInterrupted()} or {@link Thread#interrupted()}).
     */
    private static int THREAD_INTERRUPTED_STATUS_VAR_ID = metadata.getVariableId(
            "java.lang.Thread", "$interruptedStatus");

    private static final MethodHandle SYNC_COLLECTION_GET_MUTEX = getFieldGetter(
            Collections.synchronizedCollection(Collections.EMPTY_LIST).getClass(), "mutex");
    private static final MethodHandle SYNC_MAP_GET_MUTEX = getFieldGetter(
            Collections.synchronizedMap(Collections.EMPTY_MAP).getClass(), "mutex");

    private static MethodHandle getFieldGetter(Class<?> cls, String name) {
        try {
            Field field = cls.getDeclaredField(name);
            field.setAccessible(true);
            return MethodHandles.lookup().unreflectGetter(field);
        } catch (NoSuchFieldException | SecurityException | IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Map from iterator to its associated iterable (if any).
     */
    private static final SynchronizedWeakIdentityHashMap<Iterator, Iterable> iteratorToIterable = new SynchronizedWeakIdentityHashMap<>();

    /**
     * Map from view to its backed collection. There are two kinds of view in
     * the Java Collections Framework: the collection views provided in the
     * {@link java.util.Map} interface and the range views provided in the {@link java.util.List},
     * {@link java.util.SortedSet}, and {@link java.util.SortedMap} interfaces.
     */
    private static final SynchronizedWeakIdentityHashMap<Object, Object> viewToBackingCollection = new SynchronizedWeakIdentityHashMap<>();

    private static final SynchronizedWeakIdentityHashMap<Object, MutableInt> collectionToState = new SynchronizedWeakIdentityHashMap<>();

    private static ILoggingEngine logger;

    private static Configuration config;

    private RVPredictRuntime() { } // forbid instantiation

    public static void init(Configuration config, ILoggingEngine logger) {
        RVPredictRuntime.config = config;
        RVPredictRuntime.logger = logger;
    }

    public static void logClassInitializerEnter() {
        saveMetaEvent(EventType.CLINIT_ENTER, 0);
    }

    public static void logClassInitializerExit() {
        saveMetaEvent(EventType.CLINIT_EXIT, 0);
    }

    public static void logInvokeMethod(int locId) {
        if (config.stacks) {
            saveMetaEvent(EventType.INVOKE_METHOD, locId);
        }
    }

    public static void logFinishMethod(int locId) {
        if (config.stacks) {
            saveMetaEvent(EventType.FINISH_METHOD, locId);
        }
    }

    /**
     * Logs events produced by invoking {@code object.wait()}.
     *
     * @param object
     *            the {@code Object} whose {@code wait()} method is invoked
     * @param locId
     *            the location identifier of the event
     */
    public static void rvPredictWait(Object object, int locId) throws InterruptedException {
        rvPredictWait(object, 0, locId);
    }

    /**
     * Logs events produced by invoking {@code object.wait(long)}.
     *
     * @param object
     *            the {@code Object} whose {@code wait(long)} method is invoked
     * @param timeout
     *            the first argument of {@code object.wait(long)}
     * @param locId
     *            the location identifier of the event
     */
    public static void rvPredictWait(Object object, long timeout, int locId)
            throws InterruptedException {
        saveLockEvent(EventType.WAIT_REL, locId, MONITOR_C, object);
        try {
            object.wait(timeout);
        } catch (InterruptedException e) {
            clearInterruptedStatus(Thread.currentThread(), locId);
            saveLockEvent(EventType.WAIT_ACQ, locId, MONITOR_C, object);
            throw e;
        }

        saveLockEvent(EventType.WAIT_ACQ, locId, MONITOR_C, object);
    }

    /**
     * Logs events produced by invoking {@code object.wait(long, int)}.
     *
     * @param object
     *            the {@code Object} whose {@code wait(long, int)} method is
     *            invoked
     * @param timeout
     *            the first argument of {@code object.wait(long, int)}
     * @param nano
     *            the second argument of {@code object.wait(long, int)}
     * @param locId
     *            the location identifier of the event
     */
    public static void rvPredictWait(Object object, long timeout, int nano, int locId)
            throws InterruptedException {
        saveLockEvent(EventType.WAIT_REL, locId, MONITOR_C, object);
        try {
            object.wait(timeout, nano);
        } catch (InterruptedException e) {
            clearInterruptedStatus(Thread.currentThread(), locId);
            saveLockEvent(EventType.WAIT_ACQ, locId, MONITOR_C, object);
            throw e;
        }

        saveLockEvent(EventType.WAIT_ACQ, locId, MONITOR_C, object);
    }

    /**
     * Logs the {@code LOCK} event produced by entering block synchronized with
     * {@code object}'s intrinsic lock.
     *
     * @param object
     *            the {@code Object} whose intrinsic lock is acquired
     * @param locId
     *            the location identifier of the event
     */
    public static void logMonitorEnter(Object object, int locId) {
        saveLockEvent(EventType.WRITE_LOCK, locId, MONITOR_C, object);
    }

    /**
     * Logs the {@code UNLOCK} event produced by exiting block synchronized with
     * {@code object}'s intrinsic lock.
     *
     * @param object
     *            the {@code Object} whose intrinsic lock is released
     * @param locId
     *            the location identifier of the event
     */
    public static void logMonitorExit(Object object, int locId) {
        saveLockEvent(EventType.WRITE_UNLOCK, locId, MONITOR_C, object);
    }

    /**
     * Logs the {@code READ/WRITE} event produced by field access.
     *
     * @param object
     *            the owner object of the field; {@code null} when accessing
     *            static fields
     * @param value
     *            the value written by the write access or the value read by the
     *            read access
     * @param variableId
     *            the variable identifier of the field
     * @param isWrite
     *            specifies if it is a write access
     * @param locId
     *            the location identifier of the event
     */
    public static void logFieldAcc(Object object, long value, int variableId, boolean isWrite,
            int locId) {
        saveMemAccEvent(isWrite ? EventType.WRITE : EventType.READ, locId,
                System.identityHashCode(object), -variableId, value);
    }

    /**
     * Logs the {@code READ/WRITE} event produced by array access.
     *
     * @param array
     *            the array to access
     * @param index
     *            the array index
     * @param value
     *            the value written by the write access or the value read by the
     *            read access
     * @param isWrite
     *            specifies if it is a write access
     * @param locId
     *            the location identifier of the event
     */
    public static void logArrayAcc(Object array, int index, long value, boolean isWrite, int locId) {
        saveMemAccEvent(isWrite ? EventType.WRITE : EventType.READ, locId,
                System.identityHashCode(array), index, value);
    }

    /**
     * {@link Thread#start()}
     */
    public static void rvPredictStart(Thread thread, int locId) {
        saveThreadSyncEvent(EventType.START, locId, thread.getId());
        metadata.addThreadCreationInfo(thread.getId(), Thread.currentThread().getId(), locId);
        thread.start();
    }

    /**
     * {@link Thread#isAlive()}
     * <p>
     * <i>Thread termination rule:</i> Any action in a thread happens before any
     * other thread detects that thread has terminated, either by successfully
     * return from {@link Thread#join()} or by {@link Thread#isAlive()}
     * returning false.
     */
    public static boolean rvPredictIsAlive(Thread thread, int locId) {
        if (!thread.isAlive()) {
            saveThreadSyncEvent(EventType.JOIN, locId, thread.getId());
            return false;
        }
        return true;
    }

    /**
     * {@link Thread#join()}
     */
    public static void rvPredictJoin(Thread thread, int locId) throws InterruptedException {
        rvPredictJoin(thread, 0, locId);
    }

    /**
     * {@link Thread#join(long)}
     */
    public static void rvPredictJoin(Thread thread, long millis, int locId)
            throws InterruptedException {
        try {
            thread.join(millis);
        } catch (InterruptedException e) {
            clearInterruptedStatus(Thread.currentThread(), locId);
            throw e;
        }

        if (millis == 0) {
            saveThreadSyncEvent(EventType.JOIN, locId, thread.getId());
        }
    }

    /**
     * {@link Thread#join(long, int)}
     */
    public static void rvPredictJoin(Thread thread, long millis, int nanos, int locId)
            throws InterruptedException {
        try {
            thread.join(millis, nanos);
        } catch (InterruptedException e) {
            clearInterruptedStatus(Thread.currentThread(), locId);
            throw e;
        }

        if (millis == 0 && nanos == 0) {
            saveThreadSyncEvent(EventType.JOIN, locId, thread.getId());
        }
    }

    /**
     * {@link Thread#sleep(long)}
     */
    public static void rvPredictSleep(long millis, int locId) throws InterruptedException {
        try {
            Thread.sleep(millis);
        } finally {
            clearInterruptedStatus(Thread.currentThread(), locId);
        }
    }

    /**
     * {@link Thread#sleep(long,int)}
     */
    public static void rvPredictSleep(long millis, int nanos, int locId)
            throws InterruptedException {
        try {
            Thread.sleep(millis, nanos);
        } finally {
            clearInterruptedStatus(Thread.currentThread(), locId);
        }
    }

    /**
     * {@link Thread#interrupt()}
     */
    public static void rvPredictInterrupt(Thread thread, int locId) {
        if (thread != Thread.currentThread()) {
            thread.checkAccess();
        }
        setInterruptedStatus(thread, locId);
        thread.interrupt();
    }

    /**
     * {@link Thread#isInterrupted()}
     */
    public static boolean rvPredictIsInterrupted(Thread thread, int locId) {
        boolean result = thread.isInterrupted();
        testInterruptedStatus(thread, result, false /* reset */, locId);
        return result;
    }

    /**
     * {@link Thread#interrupted()}
     */
    public static boolean rvPredictInterrupted(int locId) {
        boolean result = Thread.interrupted();
        testInterruptedStatus(Thread.currentThread(), result, true /* reset */, locId);
        return result;
    }

    private static void setInterruptedStatus(Thread t, int locId) {
        saveAtomicEvent(EventType.ATOMIC_WRITE, locId, System.identityHashCode(t),
                -THREAD_INTERRUPTED_STATUS_VAR_ID, 1, 0);
    }

    private static void clearInterruptedStatus(Thread t, int locId) {
        saveAtomicEvent(EventType.ATOMIC_WRITE, locId, System.identityHashCode(t),
                -THREAD_INTERRUPTED_STATUS_VAR_ID, 0, 0);
    }

    private static void testInterruptedStatus(Thread t, boolean isInterrupted,
            boolean clearInterrupted, int locId) {
        if (clearInterrupted) {
            if (isInterrupted) {
                saveAtomicEvent(EventType.ATOMIC_READ_THEN_WRITE, locId,
                        System.identityHashCode(t), -THREAD_INTERRUPTED_STATUS_VAR_ID, 1, 0);
            } else {
                saveAtomicEvent(EventType.ATOMIC_READ, locId, System.identityHashCode(t),
                        -THREAD_INTERRUPTED_STATUS_VAR_ID, 0, 0);
            }
        } else {
            saveAtomicEvent(EventType.ATOMIC_READ, locId, System.identityHashCode(t),
                    -THREAD_INTERRUPTED_STATUS_VAR_ID, bool2int(isInterrupted), 0);
        }
    }

    /**
     * {@link System#arraycopy(Object,int,Object,int,int)}
     */
    public static void rvPredictSystemArraycopy(Object src, int srcPos, Object dest, int destPos,
            int length, int locId) {
        // 8 primitive types: boolean, byte, char, short, int, long, float, and
        // double

        if (srcPos >= 0 && destPos >= 0 && length > 0) {
            if (src instanceof Object[]) {
                if (dest instanceof Object[]) {
                    if (srcPos + length <= ((Object[]) src).length
                            && destPos + length <= ((Object[]) dest).length) {
                        int k = length;
                        for (int i = 0; i < length; i++) {
                            Object srcObj = ((Object[]) src)[i + srcPos];
                            if (srcObj == null
                                    || dest.getClass().getComponentType()
                                            .isAssignableFrom(srcObj.getClass())) {
                                logArrayAcc(src, srcPos + i, System.identityHashCode(srcObj),
                                        false, locId);
                            } else {
                                k = i;
                                break;
                            }
                        }
                        for (int i = 0; i < k; i++) {
                            logArrayAcc(dest, destPos + i, System.identityHashCode(((Object[]) src)[i + srcPos]),
                                    true, locId);
                        }
                    }
                }
            } else if (src instanceof boolean[]) {
                if (dest instanceof boolean[]) {
                    if (srcPos + length <= ((boolean[]) src).length
                            && destPos + length <= ((boolean[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, bool2int(((boolean[]) src)[i]), false, locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, ((boolean[]) src)[i - destPos + srcPos] ? 1
                                                            : 0, true, locId);
                        }
                    }
                }
            } else if (src instanceof byte[]) {
                if (dest instanceof byte[]) {
                    if (srcPos + length <= ((byte[]) src).length
                            && destPos + length <= ((byte[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, ((byte[]) src)[i], false, locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, ((byte[]) src)[i - destPos + srcPos], true, locId);
                        }
                    }
                }
            } else if (src instanceof char[]) {
                if (dest instanceof char[]) {
                    if (srcPos + length <= ((char[]) src).length
                            && destPos + length <= ((char[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, ((char[]) src)[i], false, locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, ((char[]) src)[i - destPos + srcPos], true, locId);
                        }
                    }
                }
            } else if (src instanceof short[]) {
                if (dest instanceof short[]) {
                    if (srcPos + length <= ((short[]) src).length
                            && destPos + length <= ((short[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, ((short[]) src)[i], false, locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, ((short[]) src)[i - destPos + srcPos], true, locId);
                        }
                    }
                }
            } else if (dest instanceof int[]) {
                if (srcPos + length <= ((int[]) src).length
                        && destPos + length <= ((int[]) dest).length) {
                    for (int i = srcPos; i < srcPos + length; i++) {
                        logArrayAcc(src, i, ((int[]) src)[i], false, locId);
                    }
                    for (int i = destPos; i < destPos + length; i++) {
                        logArrayAcc(dest, i, ((int[]) src)[i - destPos + srcPos], true, locId);
                    }
                }
            } else if (src instanceof long[]) {
                if (dest instanceof long[]) {
                    if (srcPos + length <= ((long[]) src).length
                            && destPos + length <= ((long[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, ((long[]) src)[i], false, locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, ((long[]) src)[i - destPos + srcPos], true, locId);
                        }
                    }
                }
            } else if (src instanceof float[]) {
                if (dest instanceof float[]) {
                    if (srcPos + length <= ((float[]) src).length
                            && destPos + length <= ((float[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, Float.floatToIntBits(((float[]) src)[i]), false,
                                    locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, Float.floatToIntBits(((float[]) src)[i - destPos + srcPos]),
                                    true,
                                    locId);
                        }
                    }
                }
            } else if (src instanceof double[]) {
                if (dest instanceof double[]) {
                    if (srcPos + length <= ((double[]) src).length
                            && destPos + length <= ((double[]) dest).length) {
                        for (int i = srcPos; i < srcPos + length; i++) {
                            logArrayAcc(src, i, Double.doubleToLongBits(((double[]) src)[i]), false,
                                    locId);
                        }
                        for (int i = destPos; i < destPos + length; i++) {
                            logArrayAcc(dest, i, Double.doubleToLongBits(((double[]) src)[i - destPos + srcPos]),
                                    true,
                                    locId);
                        }
                    }
                }
            }
        }

        System.arraycopy(src, srcPos, dest, destPos, length);
    }

    /**
     * {@link Iterable#iterator()}
     */
    public static Iterator rvPredictIterableGetIterator(Iterable iterable, int locId) {
        Iterator iterator = iterable.iterator();
        iteratorToIterable.put(iterator, iterable);
        return iterator;
    }

    /**
     * {@link List#listIterator()}
     */
    public static ListIterator rvPredictListGetListIterator(List list, int locId) {
        ListIterator listItr = list.listIterator();
        iteratorToIterable.put(listItr, list);
        return listItr;
    }

    /**
     * {@link List#listIterator(int)}
     */
    public static ListIterator rvPredictListGetListIterator(List list, int index, int locId) {
        ListIterator listItr = list.listIterator(index);
        iteratorToIterable.put(listItr, list);
        return listItr;
    }

    /**
     * {@link Iterator#hasNext()}
     */
    public static boolean rvPredictIteratorHasNext(Iterator iterator, int locId) {
        return readUsingIterator(iterator, locId, () -> {
            return iterator.hasNext();
        });
    }

    /**
     * {@link Iterator#next()}
     */
    public static Object rvPredictIteratorNext(Iterator iterator, int locId) {
        return readUsingIterator(iterator, locId, () -> {
            return iterator.next();
        });
    }

    /**
     * {@link Iterator#remove()}
     */
    public static void rvPredictIteratorRemove(Iterator iterator, int locId) {
        writeUsingIterator(iterator, locId, () -> {
            iterator.remove();
            return null;
        });
    }

    /**
     * {@link ListIterator#hasPrevious()}
     */
    public static boolean rvPredictListIteratorHasPrevious(ListIterator listItr, int locId) {
        return readUsingIterator(listItr, locId, () -> {
            return listItr.hasPrevious();
        });
    }

    /**
     * {@link ListIterator#previous()}
     */
    public static Object rvPredictListIteratorPrevious(ListIterator listItr, int locId) {
        return readUsingIterator(listItr, locId, () -> {
            return listItr.previous();
        });
    }

    /**
     * {@link ListIterator#add(Object)}
     */
    public static void rvPredictListIteratorAdd(ListIterator listItr, Object e, int locId) {
        writeUsingIterator(listItr, locId, () -> {
            listItr.add(e);
            return null;
        });
    }

    /**
     * {@link ListIterator#set(Object)}
     */
    public static void rvPredictListIteratorSet(ListIterator listItr, Object e, int locId) {
        writeUsingIterator(listItr, locId, () -> {
            listItr.set(e);
            return null;
        });
    }

    /**
     * {@link Collection#add(Object)}
     */
    public static boolean rvPredictCollectionAdd(Collection collection, Object e, int locId) {
        return logCollectionWriteAccess(collection, locId, () -> {
            return collection.add(e);
        });
    }

    /**
     * {@link Collection#addAll(Collection)}
     */
    public static boolean rvPredictCollectionAddAll(Collection collection, Collection c, int locId) {
        return logCollectionWriteAccess(collection, locId, () -> {
            return collection.addAll(c);
        });
    }

    /**
     * {@link Collection#remove(Object)}
     */
    public static boolean rvPredictCollectionRemove(Collection collection, Object e, int locId) {
        return logCollectionWriteAccess(collection, locId, () -> {
            return collection.remove(e);
        });
    }

    /**
     * {@link Collection#removeAll(Collection)}
     */
    public static boolean rvPredictCollectionRemoveAll(Collection collection, Collection c, int locId) {
        return logCollectionWriteAccess(collection, locId, () -> {
            return collection.removeAll(c);
        });
    }

    /**
     * {@link Collection#retainAll(Collection)}
     */
    public static boolean rvPredictCollectionRetainAll(Collection collection, Collection c, int locId) {
        return logCollectionWriteAccess(collection, locId, () -> {
            return collection.retainAll(c);
        });
    }

    /**
     * {@link Collection#contains(Object)}
     */
    public static boolean rvPredictCollectionContains(Collection collection, Object e, int locId) {
        return logCollectionReadAccess(collection, locId, () -> {
            return collection.contains(e);
        });
    }

    /**
     * {@link Collection#containsAll(Collection)}
     */
    public static boolean rvPredictCollectionContainsAll(Collection collection, Collection c, int locId) {
        return logCollectionReadAccess(collection, locId, () -> {
            return collection.containsAll(c);
        });
    }

    /**
     * {@link java.util.Collection#clear()}
     */
    public static void rvPredictCollectionClear(Collection collection, int locId) {
        logCollectionWriteAccess(collection, locId, () -> {
            collection.clear();
            return null;
        });
    }

    /**
     * {@link Collection#toArray()}
     */
    public static Object[] rvPredictCollectionToArray(Collection collection, int locId) {
        return logCollectionReadAccess(collection, locId, () -> {
            return collection.toArray();
        });
    }

    /**
     * {@link Collection#toArray(Object[])}
     */
    public static Object[] rvPredictCollectionToArray(Collection collection, Object[] a, int locId) {
        return logCollectionReadAccess(collection, locId, () -> {
            return collection.toArray(a);
        });
    }

    /**
     * {@link Map#get(Object)}
     */
    public static Object rvPredictMapGet(Map map, Object key, int locId) {
        return logCollectionReadAccess(map, locId, () -> {
            return map.get(key);
        });
    }

    /**
     * {@link Map#put(Object, Object)}
     */
    public static Object rvPredictMapPut(Map map, Object key, Object value, int locId) {
        return logCollectionWriteAccess(map, locId, () -> {
            return map.put(key, value);
        });
    }

    /**
     * {@link Map#putAll(Map)}
     */
    public static void rvPredictMapPutAll(Map map, Map m, int locId) {
        logCollectionWriteAccess(map, locId, () -> {
            map.putAll(m);
            return null;
        });
    }

    /**
     * {@link Map#remove(Object)}
     */
    public static Object rvPredictMapRemove(Map map, Object key, int locId) {
        return logCollectionWriteAccess(map, locId, () -> {
            return map.remove(key);
        });
    }

    /**
     * {@link Map#containsKey(Object)}
     */
    public static boolean rvPredictMapContainsKey(Map map, Object key, int locId) {
        return logCollectionReadAccess(map, locId, () -> {
            return map.containsKey(key);
        });
    }

    /**
     * {@link Map#containsValue(Object)}
     */
    public static boolean rvPredictMapContainsValue(Map map, Object value, int locId) {
        return logCollectionReadAccess(map, locId, () -> {
            return map.containsValue(value);
        });
    }

    /**
     * {@link Map#clear()}
     */
    public static void rvPredictMapClear(Map map, int locId) {
        logCollectionWriteAccess(map, locId, () -> {
            map.clear();
            return null;
        });
    }

    /**
     * {@link Map#entrySet()}
     */
    public static Set rvPredictMapEntrySet(Map map, int locId) {
        Set result = map.entrySet();
        viewToBackingCollection.put(result, map);
        return result;
    }

    /**
     * {@link Map#keySet()}
     */
    public static Set rvPredictMapKeySet(Map map, int locId) {
        Set result = map.keySet();
        viewToBackingCollection.put(result, map);
        return result;
    }

    /**
     * {@link Map#values()}
     */
    public static Collection rvPredictMapValues(Map map, int locId) {
        Collection result = map.values();
        viewToBackingCollection.put(result, map);
        return result;
    }

    /**
     * {@link Collections#synchronizedCollection(Collection)}
     */
    public static Collection rvPredictSynchronizedCollection(Collection collection, int locId) {
        Collection syncCollection = Collections.synchronizedCollection(collection);
        viewToBackingCollection.put(syncCollection, collection);
        return syncCollection;
    }

    /**
     * {@link Collections#synchronizedMap(Map)}
     */
    public static Map rvPredictSynchronizedMap(Map map, int locId) {
        Map syncMap = Collections.synchronizedMap(map);
        viewToBackingCollection.put(syncMap, map);
        return syncMap;
    }

    private static int bool2int(boolean b) {
        return b ? 1 : 0;
    }

    private static <T> T logCollectionReadAccess(Object collection, int locId, Supplier<T> closure) {
        return logCollectionAccess(collection, false, locId, closure);
    }

    private static <T> T logCollectionWriteAccess(Object collection, int locId, Supplier<T> closure) {
        return logCollectionAccess(collection, true, locId, closure);
    }

    /**
     * Logs event generated by accessing the (abstract) state of a collection
     * object.
     *
     * @param collection
     *            the collection
     * @param locId
     *            the location identifier
     */
    public static <T> T logCollectionAccess(Object collection, boolean isWrite, int locId,
            Supplier<T> closure) {
        String cname = collection.getClass().getName();
        if (cname.startsWith("com.runtimeverification")) {
            /* skip our own runtime library class which has been manually instrumented */
            return closure.get();
        }

        Object backingColl = getBackingCollection(collection);
        MutableInt state = getCollectionState(backingColl);

        Object mutex = null;
        boolean isThreadSafe = true;
        if (collection instanceof Vector || collection instanceof Hashtable) {
            mutex = collection;
        } else if (collection instanceof BlockingQueue
                || collection instanceof ConcurrentMap
                || cname.contains("Concurrent")) {
            mutex = state;
        } else if (cname.startsWith("java.util.Collections$Synchronized")) {
            try {
                mutex = collection instanceof Collection
                        ? SYNC_COLLECTION_GET_MUTEX.invoke(collection)
                        : SYNC_MAP_GET_MUTEX.invoke(collection);
            } catch (Throwable e) {
                throw new RuntimeException(e);
            }
        } else {
            /* unknown collection; assume non-thread-safe */
            mutex = state;
            isThreadSafe = false;
        }

        int addrl = System.identityHashCode(backingColl);
        int addrr = -metadata.getVariableId(backingColl.getClass().getName(), MOCK_STATE_FIELD);
        synchronized (mutex) {
            int value = state.intValue();
            if (isThreadSafe) {
                saveLockEvent(EventType.WRITE_LOCK, locId, MONITOR_C, mutex);
            }
            if (isWrite) {
                state.increment();
                saveMemAccEvent(EventType.READ, locId, addrl, addrr, value);
                saveMemAccEvent(EventType.WRITE, locId, addrl, addrr, value + 1);
            } else {
                saveMemAccEvent(EventType.READ, locId, addrl, addrr, value);
            }
            if (isThreadSafe) {
                saveLockEvent(EventType.WRITE_UNLOCK, locId, MONITOR_C, mutex);
            }
            return closure.get();
        }
    }

    /**
     * Gets the backing {@link Collection} or {@link Map} of a given view.
     */
    private static Object getBackingCollection(Object view) {
        Object backingColl;
        while ((backingColl = viewToBackingCollection.get(view)) != null) {
            view = backingColl;
        }
        return view;
    }

    private static MutableInt getCollectionState(Object collection) {
        return collectionToState.computeIfAbsent(collection, x -> new MutableInt(0));
    }

    /**
     * Logs write event generated by accessing some collection (e.g.
     * {@link Collection}, {@link Map}, etc.) using an {@link Iterator}.
     */
    private static <T> T writeUsingIterator(Iterator iterator, int locId, Supplier<T> closure) {
        Object collection = resolveAccessedCollection(iterator);
        if (collection != null) {
            return logCollectionWriteAccess(collection, locId, closure);
        } else {
            return closure.get();
        }
    }

    /**
     * Logs read event generated by accessing some collection (e.g.
     * {@link Collection}, {@link Map}, etc.) using an {@link Iterator}.
     */
    private static <T> T readUsingIterator(Iterator iterator, int locId, Supplier<T> closure) {
        Object collection = resolveAccessedCollection(iterator);
        if (collection != null) {
            return logCollectionReadAccess(collection, locId, closure);
        } else {
            return closure.get();
        }
    }

    private static Set<String> DEBUG_ORPHAN_ITERATORS = Collections.newSetFromMap(new ConcurrentHashMap<>());

    /**
     * Returns the {@link Collection} or {@link Map} that a given
     * {@link Iterator} is accessing or {@code null} if the accessed collection
     * is not available.
     */
    private static Object resolveAccessedCollection(Iterator iterator) {
        Iterable iterable = iteratorToIterable.get(iterator);
        if (iterable == null) {
            /* not all iterators are created by Iterable.iterator() */
            if (DEBUG_ORPHAN_ITERATORS.add(iterator.getClass().getName())) {
                config.logger().debug("Unable to find the collection accessed by " + iterator);
            }
            return null;
        } else {
            return getBackingCollection(iterable);
        }
    }

    public static void saveMemAccEvent(EventType eventType, int locId, int addrl, int addrr,
            long value) {
        logger.log(eventType, locId, addrl, addrr, value, 0);
    }

    public static void saveThreadSyncEvent(EventType eventType, int locId, long tid) {
        logger.log(eventType, locId, (int) (tid >> 32), (int) tid, 0, 0);
    }

    public static void saveLockEvent(EventType eventType, int locId, byte LOCK_TYPE, Object lock) {
        if (lock == null) {
            throw new NullPointerException();
        }
        logger.log(eventType, locId, LOCK_TYPE, System.identityHashCode(lock), 0, 0);
    }

    private static void saveMetaEvent(EventType eventType, int locId) {
        logger.log(eventType, locId, 0, 0, 0, 0);
    }

    public static void saveAtomicEvent(EventType eventType, int locId, int addrl, int addrr,
            long value1, long value2) {
        logger.log(eventType, locId, addrl, addrr, value1, value2);
    }

}
